import { Poppins } from 'next/font/google'
import "./globals.css";
import Header from "@/components/shared/Header";
import SideNav from '@/components/shared/SideNav';
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})


export const metadata = {
  title: "Honkai: Star Rail",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=''>
      <body className={poppins.className }>
      {children}</body>
    </html>
  );
}
